// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNT1ifysJZIaDcXBEbfQ1_xcP0tny5GIE',
    appId: '1:1003182928392:web:dd08f89382ba88776d57bd',
    messagingSenderId: '1003182928392',
    projectId: 'infinitypizza-1010',
    authDomain: 'infinitypizza-1010.firebaseapp.com',
    storageBucket: 'infinitypizza-1010.firebasestorage.app',
    measurementId: 'G-JBZ6C2LBZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9av8A_DDhU2x9dtKDEpXsgLO6qYgOW44',
    appId: '1:1003182928392:android:9bf5ed786869aea06d57bd',
    messagingSenderId: '1003182928392',
    projectId: 'infinitypizza-1010',
    storageBucket: 'infinitypizza-1010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_AkpoApsVPXZLaNM-UVF50XIQoh4X8Fk',
    appId: '1:1003182928392:ios:cbf2855762175b8c6d57bd',
    messagingSenderId: '1003182928392',
    projectId: 'infinitypizza-1010',
    storageBucket: 'infinitypizza-1010.firebasestorage.app',
    iosBundleId: 'com.example.appClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_AkpoApsVPXZLaNM-UVF50XIQoh4X8Fk',
    appId: '1:1003182928392:ios:cbf2855762175b8c6d57bd',
    messagingSenderId: '1003182928392',
    projectId: 'infinitypizza-1010',
    storageBucket: 'infinitypizza-1010.firebasestorage.app',
    iosBundleId: 'com.example.appClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNT1ifysJZIaDcXBEbfQ1_xcP0tny5GIE',
    appId: '1:1003182928392:web:661c5bedc3f8cb946d57bd',
    messagingSenderId: '1003182928392',
    projectId: 'infinitypizza-1010',
    authDomain: 'infinitypizza-1010.firebaseapp.com',
    storageBucket: 'infinitypizza-1010.firebasestorage.app',
    measurementId: 'G-2JDWCSP7GW',
  );
}
